### ISSUE TITLE
Bug in get_data  and get_hash

### ISSUE THREAD

**Issue by HongThatCong** [mandiant/speakeasy#85]
File: windows/fileman.py, line: 89
Sometime, get_data return None, so get_hash will failed.
I think we should always check get_data return value, or get_data return b""
Thanks

**Comment by ggold7046** [comment]
Is this issue still open ?

**Comment by williballenthin** [comment]
the call to `get_data` is here: https://github.com/mandiant/speakeasy/blob/6e2c805c5d7a225785e461c22d7c33e06c857652/speakeasy/windows/fileman.py#L100

i dont see how `get_data` can return None, but its possible i'm missing something. @HongThatCong if you can provide a test case, happy to fix this. otherwise, i'm going to close this issue because i dont think its still valid today.
